---
- name: "Site {{site}} | Create site"
  sudo: yes
  template:
    src: default-site
    dest: "{{nginx_available_sites_dir}}/{{site}}"
  when: state is not defined or state in ['present', 'enabled']
  notify: reload nginx
  tags:
    - nginx
    - frontend
    - conf
    - sites

- name: Disable the default site
  file:
    path: "{{nginx_conf_dir}}/sites-enabled/default"
    state: absent
  notify:
    - reload nginx

- name: "Site {{site}} | Set site as {{'enabled' if (state is not defined or state == 'enabled') else 'disabled'}}"
  sudo: yes
  file:
    src: "{{nginx_available_sites_dir}}/{{site}}"
    dest: "{{nginx_enabled_sites_dir}}/{{site}}"
    state: "{{'link' if (state is not defined or state == 'enabled') else 'absent'}}"
  notify: reload nginx
  tags:
    - nginx
    - frontend
    - conf
    - sites
    
