- name: install rabbitmq server
  sudo: yes
  apt: name=rabbitmq-server

- rabbitmq_vhost:
    name: "{{ rabbitmq_vhost }}"
    state: present

- rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_user_password }}"
    vhost: "{{ rabbitmq_vhost }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present