---

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

# Upgrade virtualenv
- pip:
    name: virtualenv
    extra_args: --upgrade

- name: Create the virtualenv
  command: . /usr/local/bin/virtualenvwrapper.sh && mkvirtualenv -a /vagrant/ -p /usr/bin/python3.4 {{ virtualenv_name }}
           creates={{ virtualenv_path }}/bin/activate executable=/bin/bash

- name: Install packages required by the app inside virtualenv
  pip: 
    virtualenv: "{{ virtualenv_path }}"
    requirements: "{{ requirements_file }}"
    virtualenv_python: "python3.4"